### ISSUE TITLE
Unable to yarn install

### ISSUE THREAD

**Issue by shanemcgraw** [Addepar/addepar-style-toolbox#32]
When cloning down the repo and running `yarn install` for the first time, I receive this yarn error:

error An unexpected error occurred: "https://addepar.jfrog.io/addepar/api/npm/npm/@addepar/eslint-config/-/eslint-config-4.0.1.tgz?dl=https://registry.yarnpkg.com/@addepar/eslint-config/-/eslint-config-4.0.1.tgz: Request failed \"401 Unauthorized\"".

It appears that https://addepar.jfrog.io/addepar/api/npm/npm/@addepar/eslint-config/-/eslint-config-4.0.1.tgz?dl=https://registry.yarnpkg.com/@addepar/eslint-config/-/eslint-config-4.0.1.tgz is unable to be downloaded.

**Comment by mixonic** [comment]
@shanemcgraw This is just wrong. I can push a new yarn which should use only public releases.

This is a side-effect of our dev setup at Addepar. We shouldn't be leaking this into public repo lockfiles.

**Comment by shanemcgraw** [comment]
Lovely- thanks very much!
